### ISSUE TITLE
Getting this board to work??

### ISSUE THREAD

**Issue by Ghuru42** [will127534/Raspberry-Pi-PCM5122-DAC-Board#1]
Hi.

I built a board that uses you schematic and are wondering if you ever got this board working?
My first issue was to fix the i2c adress, AD0 should be high for the hifi-dac+ driver to find the board.
But even so I cant get the chip to work, the driver gives error -517.
Trying out the PlainDAC applications the i2c does not seam to work 100% either..
i2cdetect find the chip.
PlainDAC says it find the chip and prints data, it also says it can init the chip.

Any suggestions??

**Comment by will127534** [comment]
Yes I have tried this on RPI,using iqaudio driver and VOLUMIO
How about solder PCM5122 on a SSOP breakout and try the connection first?

like this [http://4.bp.blogspot.com/--DTW529Ob9U/U60DoqiZ9fI/AAAAAAAAC_k/cg2HcvpOzPY/s1600/DSC09571.jpg](http://4.bp.blogspot.com/--DTW529Ob9U/U60DoqiZ9fI/AAAAAAAAC_k/cg2HcvpOzPY/s1600/DSC09571.jpg)

**Comment by Ghuru42** [comment]
Thank you for replying.

I pretty much did that before making my board, just to make sure that the drivers did not check the i2c eeprom or similar.
And since the chip is alive via i2c, and it responds to me changing the adress, it has to be something with the i2s lines that are wrong..
I just tried removing the 1k resistors, seen other schematics that did not have them, no change.

**Comment by will127534** [comment]
The 1K resistors is just for damping the i2S bus, definitely fine to remove them.
You said that you have tried perfboard for testing, then I think the sch are fine,
and the problem maybe is the PCB board itself.

Just note that you can order this pcb on OSHpark, I've sharing at there [PCB].(https://oshpark.com/shared_projects/MmVdE7fl)

**Comment by Ghuru42** [comment]
Turned out the chip was working as it should, just that the dmesg fooled me with a bunch of errors in the recent kernel. Connected a HiFi berry card and it showed the same errors, but worked..
So turns out it's my analog section after the pcm that is messed up, a small headphone amp and a 1W speaker amp.
But thanks for the help :-)

**Comment by will127534** [comment]
Okay then,I'll close the issue.
Have fun :)
